language: python
python: "2.7"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-apt python-pycurl
install:
  - pip install ansible
  - ansible --version
script:
  - echo localhost > inventory
  - ansible-playbook -i inventory --syntax-check --list-tasks provisioning/vagrant.yml
  - ansible-playbook -i inventory --connection=local --extra-vars "mongooseim_version=1.4.0-1" --sudo -vvvv provisioning/travis.yml