language: python
python: "2.7"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-apt python-pycurl
install:
  - pip install ansible
  - ansible --version
script:
  - ansible-playbook -i provisioning/travis_inventory --syntax-check --list-tasks provisioning/vagrant.yml
  - ansible all -i provisioning/travis_inventory -m setup
  - ansible-playbook -i provisioning/travis_inventory --connection=local --extra-vars "mongooseim_version=1.4.0-1" --sudo -vvvv provisioning/travis.yml