- name: Create the VPC
  ec2_vpc: >
    state=present
    cidr_block={{vpc_cidr_block}}
    subnets={{vpc_subnets}}
    resource_tags={"Environment": "xmpp-server-benchmark"}
    wait=yes
  register: ec2_vpc

- name: Open up SSH for us using a security group
  ec2_group: >
    name=ansible_xmpp_server_benchmark_group
    description=Allows SSH connections
    vpc_id={{ec2_vpc.id}}
    rules=
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 0.0.0.0/0

- name: Provision tsung client instance
  ec2: >
    instance_type={{instance_type}}
    image={{image}}
    wait=yes
    group=ansible_xmpp_server_benchmark_group
    count={{client_count}}
    vpc_subnet_id={{item.id}}
    instance_tags={"Name": "Tsung Clients"}
    state=present
  register: ec2_client
  with_items: ec2_vpc.subnets

- name: Provision a set of server instances
  ec2: >
    group=ansible_xmpp_server_benchmark_group
    instance_type={{instance_type}}
    image={{image}}
    wait=yes
    count={{server_count}}
    vpc_subnet_id={{item.id}}
    instance_tags={"Name": "XMPP Servers"}
    state=present
  register: ec2
  with_items: ec2_vpc.subnets

- name: Add all instance public IPs to host group
  add_host: hostname={{ item.public_ip }} groupname=clients
  with_items: ec2_client.instances

- name: Add all instance public IPs to host group
  add_host: hostname={{ item.public_ip }} groupname=servers
  with_items: ec2.instances