- name: remove possible old keys
  command: rm ~/.ssh/id_rsa_ansible ~/.ssh/id_rsa_ansible.pub
  ignore_errors: true

- name: generate authorized key
  command: "ssh-keygen -N \"\" -t rsa -f ~/.ssh/id_rsa_ansible"

- name: copy public key
  command: "ssh-keygen -y -f ~/.ssh/id_rsa_ansible"
  register: ssh_public_key

- name: add authorized key
  shell: "echo '{{ssh_public_key.stdout}}' >> /root/.ssh/authorized_keys"
  #delegate_to: "{{hostvars[item]['ansible_ssh_user']}}@{{item}}"
  delegate_to: "{{item}}"
  with_items: groups['servers']
