- hosts: localhost
  connection: local
  gather_facts: False
  vars_files:
    - group_vars/ec2
  roles:
    - ec2

- hosts: clients
  sudo: true
  vars_files:
    - group_vars/tsung
  roles:
    - tsung

- hosts: servers
  sudo: true
  vars_files:
    - group_vars/xmpp
  roles:
    - ejabberd
    - mongooseim