# servers before clients
# little trick in order to have all the infos necessary in the hostvars
# before running the scenarios role.
- hosts: servers
  sudo: true
  vars_files:
    - group_vars/xmpp
  roles:
    - ejabberd
    - mongooseim

- hosts: clients
  sudo: true
  vars_files:
    - group_vars/tsung
  roles:
    - tsung
    - scenarios
    - add_authorized_key
