- hosts: clients
  sudo: true
  vars_files:
    - group_vars/tsung
  roles:
    - tsung
    - scenarios
    - add_authorized_key

- hosts: servers
  sudo: true
  vars_files:
    - group_vars/xmpp
  roles:
    - ejabberd
    - mongooseim
