- hosts: all
  sudo: true
  vars_files:
    - group_vars/tsung
  roles:
    - tsung
    - scenarios

- hosts: all
  sudo: true
  vars_files:
    - group_vars/xmpp
  roles:
    - ejabberd
    - mongooseim

- hosts: all
  sudo: true
  roles:
    - prepare_results_dir
    - start_ejabberd_test
    - start_mongooseim_test